### PR TITLE
feat/givecreds

### PR DESCRIPTION
**Pull request by MaxTretikov**

### CODE REVIEW

**Comment by alexrandaccio** [comment]
This looks great, Max! Excellent work.

I want to test this out with docker, but services/index.ts is throwing:
"export 'default' (reexported as 'Password') was not found in './Password'.

Is it working for you/do you have a quick fix for exporting your password module correctly?

**Comment by MaxTretikov** [comment]
Everything should be fixed - lot of errors hiding in that Pandora's box. Sorry for the force push, tried to ``git commit --amend`` ad push normally but git can be finicky.

About the docker: the reason I was MIA for a couple days after our call was because I was trying to set up the docker. Eventually I gave up and started everything individually but I have no idea how it works on your machine because it failed on 3 of mine. It might be a mac-only thing?

**Comment by alexrandaccio** [comment]
No worries! I have had my share of fights with Docker as well. To clarify--are you running windows?

**Comment by MaxTretikov** [comment]
I tried to run the docker on my raspi4, my debian dual boot, and WSL. Now that I'm thinking about it, it's a very debian-centric lineup, which might have something to do with it.

**Comment by alexrandaccio** [comment]
I see. I know of downloads for mac, windows, and linux but can't vouch for anything else.

**Comment by alexrandaccio** [comment]
Have you been able to get the emails to work? If so, what API key are you using? I am getting 'invalid API key' from mandrill when I use our mailchimp API key.

**Comment by MaxTretikov** [comment]
I believe it's because RXC_EMAIL is set to "you@example.com". I don't know what email mailchimp is supposed to be sending from, so I left it as the default for the time being. I *think* mandrill checks API key against email, and it sees that you@example has no API key. If entering the RXC mailchimp email doesn't work then I'll take a closer look.

**Comment by alexrandaccio** [comment]
got it, thanks

**Comment by alexrandaccio** [comment]
Can you send me whatever mandrill API reference you are looking at? I believe all our emails come from info@radicalxchange.org, but that's not working.

**Comment by alexrandaccio** [comment]
by the way I changed the API key, it is now at the bottom of the task management google doc

**Comment by MaxTretikov** [comment]
I set up a mailchimp account on my own domain to check out how everything is looking on your end. My mailchimp needs time to update my DNS records but I think the problem is that Mailchimp and Mandrill/Transactional have different API keys, and the one we're using is a mailchimp key.

**Comment by alexrandaccio** [comment]
Ok. Since it won't really change any existing functionality on master, I'm going to say that if you can get the emails to work from your domain, you can merge this. Let me know how it goes.

Great work all around! Thanks so much for taking this on. Wishing you and your family a very happy and healthy New Year!

**Pull request merged**
